#!/bin/sh

# handle initramfs-tools prereq (not yet)
case "${1}" in
	prereqs)
		exit 0
	;;
esac

set -x #FIXME: use better initramfs-tools log/debug tools

for x in $(cat /proc/cmdline)
do
	case $x in
		cowpath=*)
			COW_PATH=${x#cowpath=}
		;;
		nfsopts=*)
			NFSOPTS=${x#nfsopts=}
		;;
		cowopt=*)
			COW_OPT=${x#cowopt=}
		;;
		cowdev=*)
			COW_DEV=${x#cowdev=}
		;;
	esac
done

# Do we want a full overlay or rather just /etc /var and /root overlayed 
if echo ${COW_OPT} | egrep -q '^full,|,full$|^full$|,full,'
then
	COW_FULL=1
	COW_OPT="$(echo "${COW_OPT}" | sed 's/full//;s/^,//;s/,$//;s/,,/,/')"
fi

#	env
#	set -x

# Bare minimum to kick in
if [ -z "${COW_PATH}" ] && [ -z "${COW_DEV}" ]
then
	return 0
fi

# In the case of a full overlay, we move mounted /root out of the way to build the stack and provide access to pristine root
if [ -n "${COW_FULL}" ]
then
	tmproot=/tmproot
	mkdir -p ${tmproot}
	mount --bind --make-rprivate /${rootmnt} ${tmproot} # FIXME : rprivate does not seem to work in this context
	umount /${rootmnt}
	cowp=${tmproot}/lib/live/cow
else
	cowp=${rootmnt}/lib/live/cow
fi

# We bail out if we do not have anywhere to mount the stack
[ -d "${cowp}" ] || exit 1

case ${COW_DEV} in
	nfs://*)
		NFS_COW=${COW_DEV#nfs://}
		mac=$(ip -o li sh | egrep ether | head -1 | sed 's/.*link\/ether \([0-9a-f:]\+\) .*/\1/;y/:/-/')
		nfs_mtp=${NFS_COW}/${mac}
		if [ -n "${NFSOPTS}" ]
		then
			nfsopts=nolock,${NFSOPTS}
		else
			nfsopts="vers=3,nolock"
		fi
		mount -o ${nfsopts} ${nfs_mtp} ${cowp} || return 3
		break
	;;
	/dev/*)
		if ! [ -e "${COW_DEV}" ] && [ -x /sbin/lvm ]
		then
			lvm lvchange --ignorelockingfailure -ay "${COW_DEV}" || return 5
		fi
		#e2fsck -fy ${COW_DEV}
		if [ -n "${COW_OPT}" ]
		then
			cow_opt="-o ${COW_OPT}"
		else
			unset cow_opt
		fi
		mount -t ext4 ${cow_opt} ${COW_DEV} ${cowp} || return 4
		break
	;;
	*)	
		mount -t tmpfs none ${cowp}
		if [ -n "${COW_PATH}" ] 
		then
			for cowpth in /${rootmnt}/live/bck/${COW_PATH} ${COW_PATH} ${cowp}/${COW_PATH}
			do
				[ -f ${cowpth} ] && tar zxf ${cowpth} -C ${cowp} && break
			done
		fi
	;;
esac

if [ -d "${cowp}/pld" ]
then
	mcowp="${cowp}/pld"
else
	mcowp="${cowp}"
fi

if [ -n "${COW_FULL}" ]
then
	mount -t overlay -o lowerdir=${tmproot},workdir=${cowp}/wrk,upperdir=${mcowp} none /${rootmnt} || exit 8

	mount --bind --make-rprivate ${tmproot} /${rootmnt}/lib/live/image || exit 9
	mount --bind --make-rprivate ${cowp} /${rootmnt}/lib/live/cow || exit 10

	umount ${cowp} || exit 11
	umount ${tmproot} || exit 12

else
	for mtp in etc var root
	do
		optst="upperdir=${mcowp}/${mtp},lowerdir=/${rootmnt}/${mtp},workdir=${cowp}/work/${mtp}"
		#[ -n "${auxopt}" ] && optst=${auxopt},${optst}
		mkdir -p ${cowp}/${mtp} ${cowp}/work/${mtp}
		mount -t overlay -o ${optst} none /${rootmnt}/${mtp} || return 5
	done
fi

#mount -t tmpfs none /tmp #now handled by systemd

exit 0
